# Build to copy to scripts.nordicenergy.io apache home directory

image: instrumentisto/rsync-ssh

pipelines:
  default:
    - step:
#        caches:
#          - composer
        script:
          #Copy the files to the target host
          - rsync -rlv --exclude '.git' . deployer@scripts.nordicenergy.co:/var/www/html/syndicated-loan

          #Change access permissions, so that the apache user has write access
          - ssh deployer@scripts.nordicenergy.co 'chmod -fcR g+rw /var/www/html/syndicated-loan/*' || true

          #Ensure the config file is used
          #- ssh deployer@scripts.nordicenergy.co 'mv /var/www/html/config.inc-DEPLOY.php /var/www/html/config.inc.php'
